version: "3"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - /home/ubuntu/docker/achacha_django/.static_root:/static
      
    depends_on:
      - achacha
    restart: always

  achacha:
    container_name: achacha
    build: ./achacha_django
    command: gunicorn --bind 0.0.0.0:8000 ACHACHA.wsgi:application
    expose:
      - "8000"
    # 변경사항이 있을 때마다 restart
    restart: always
    env_file: /home/ubuntu/gitfile/ACHACHA_PROJECT/environment/.env
