version: "3"
services:
  nginx:
    container_name: nginx
    build: ./Nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx:/etc/nginx/conf.d/
      - /home/ubuntu/gitProject/2023_achacha/Application/Django/.static_root:/static
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - achacha
    restart: always

  achacha:
    container_name: achacha
    build: ./Django
    command: gunicorn --bind 0.0.0.0:8000 ACHACHA.wsgi:application
    expose:
      - "8000"
    # 변경사항이 있을 때마다 restart
    restart: always
    env_file: /home/ubuntu/gitProject/2023_achacha/Application/Django/ACHACHA/.env