# Generated by Django 3.2.15 on 2023-02-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchachaDeals',
            fields=[
                ('achacha_deals_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_fk', models.CharField(max_length=45)),
                ('posts_fk', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'achacha_deals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LostItems',
            fields=[
                ('lost_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('lost_item', models.CharField(blank=True, max_length=150, null=True)),
                ('find_place', models.CharField(blank=True, max_length=45, null=True)),
                ('find_date', models.DateField(blank=True, null=True)),
                ('loster', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('images_fk', models.CharField(max_length=45)),
                ('center_name', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('pickup_center_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'lost_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('posts_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_fk', models.CharField(max_length=45)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('acha_money', models.IntegerField(blank=True, null=True)),
                ('delivery_way', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('lost_items_fk', models.IntegerField()),
                ('image_src', models.CharField(blank=True, max_length=150, null=True)),
                ('pickup_center', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
