# Generated by Django 3.2.15 on 2023-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('alarms_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_fk', models.CharField(max_length=45)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('image_src', models.CharField(blank=True, max_length=150, null=True)),
                ('alarm_check', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'alarms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LostItems',
            fields=[
                ('lost_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('lost_item', models.CharField(blank=True, max_length=150, null=True)),
                ('find_place', models.CharField(blank=True, max_length=45, null=True)),
                ('find_date', models.DateField(blank=True, null=True)),
                ('loster', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(blank=True, max_length=45, null=True)),
                ('images_fk', models.CharField(max_length=45)),
                ('center_name', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('pickup_center_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'lost_items',
                'managed': False,
            },
        ),
    ]
