# Generated by Django 3.2.15 on 2023-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('mail_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_group', models.CharField(blank=True, max_length=45, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
